/* Report assembly, scoring, and export (share sheet / clipboard / file). */
import { store } from './store.js';
import { toast } from './ui.js';
import { severity, describe } from './obd/dtc.js';

/** 0-100 health score from a finished car scan. */
export function scoreCar(scan) {
  let s = 100;
  const codes = [...(scan.dtc?.stored || []), ...(scan.dtc?.permanent || [])];
  for (const c of codes) {
    s -= { critical: 26, major: 15, minor: 7 }[severity(c)] ?? 10;
  }
  s -= (scan.dtc?.pending || []).length * 4;
  if (scan.status?.mil) s -= 10;

  const notReady = (scan.status?.monitors || []).filter((m) => m.supported && !m.ready).length;
  s -= Math.min(12, notReady * 3);

  const v = scan.live?.voltage ?? scan.voltage;
  if (Number.isFinite(v)) {
    if (v < 11.6 || v > 15.2) s -= 14;
    else if (v < 12.2 || v > 14.9) s -= 6;
  }
  const ct = scan.live?.coolant;
  if (Number.isFinite(ct) && ct >= 110) s -= 10;

  for (const k of ['stft1', 'ltft1', 'stft2', 'ltft2']) {
    const t = scan.live?.[k];
    if (Number.isFinite(t) && Math.abs(t) >= 25) s -= 6;
  }
  return Math.max(0, Math.min(100, Math.round(s)));
}

/** 0-100 score from a device/system test run. */
export function scoreTests(tests) {
  const graded = tests.filter((t) => ['ok', 'warn', 'bad'].includes(t.state));
  if (!graded.length) return 0;
  const pts = graded.reduce((a, t) => a + (t.state === 'ok' ? 1 : t.state === 'warn' ? 0.55 : 0), 0);
  return Math.round((pts / graded.length) * 100);
}

export function verdict(score) {
  if (score >= 90) return { label: 'Healthy', tone: 'ok' };
  if (score >= 75) return { label: 'Minor issues', tone: 'ok' };
  if (score >= 55) return { label: 'Needs attention', tone: 'warn' };
  if (score >= 30) return { label: 'Problems found', tone: 'bad' };
  return { label: 'Serious faults', tone: 'bad' };
}

/** Render a report as plain text — what gets shared, copied or saved. */
export function toText(r) {
  const L = [];
  const line = (k, v) => { if (v !== undefined && v !== null && v !== '') L.push(`${k}: ${v}`); };

  L.push('OMNIDX DIAGNOSTICS REPORT');
  L.push('='.repeat(34));
  line('Type', r.title);
  line('Date', new Date(r.ts).toLocaleString());
  line('Score', `${r.score}/100 — ${verdict(r.score).label}`);
  L.push('');

  if (r.kind === 'car') {
    L.push('-- VEHICLE --');
    line('VIN', r.data.vin);
    line('Protocol', r.data.info?.protocol);
    line('Adapter', r.data.info?.adapter);
    line('Battery', r.data.voltage ? `${r.data.voltage.toFixed(1)} V` : null);
    line('Check-engine light', r.data.status ? (r.data.status.mil ? 'ON' : 'off') : null);
    L.push('');

    const groups = [['STORED', r.data.dtc?.stored], ['PENDING', r.data.dtc?.pending], ['PERMANENT', r.data.dtc?.permanent]];
    for (const [name, codes] of groups) {
      if (!codes?.length) continue;
      L.push(`-- ${name} CODES (${codes.length}) --`);
      for (const c of codes) L.push(`  ${c}  [${severity(c)}]  ${describe(c)}`);
      L.push('');
    }
    if (!groups.some(([, c]) => c?.length)) { L.push('-- CODES --'); L.push('  None stored.'); L.push(''); }

    const notReady = (r.data.status?.monitors || []).filter((m) => m.supported && !m.ready);
    if (notReady.length) {
      L.push('-- READINESS MONITORS NOT COMPLETE --');
      for (const m of notReady) L.push(`  ${m.name}`);
      L.push('');
    }

    if (r.data.live && Object.keys(r.data.live).length) {
      L.push('-- LIVE DATA --');
      for (const [k, v] of Object.entries(r.data.live)) {
        L.push(`  ${k}: ${typeof v === 'number' ? Number(v.toFixed(2)) : v}`);
      }
      L.push('');
    }
  } else {
    for (const t of r.data.tests || []) {
      const mark = { ok: '[PASS]', warn: '[WARN]', bad: '[FAIL]' }[t.state] || '[ -- ]';
      L.push(`${mark} ${t.name}${t.detail ? ` — ${t.detail}` : ''}`);
    }
    L.push('');
    if (r.data.facts?.length) {
      L.push('-- DETAILS --');
      for (const [k, v] of r.data.facts) L.push(`  ${k}: ${v}`);
      L.push('');
    }
  }

  L.push('Generated by OmniDx. Informational only —');
  L.push('confirm faults with a qualified technician before repairs.');
  return L.join('\n');
}

export function save(kind, title, score, data, vehicleId = null) {
  return store.saveReport({ kind, title, score, data, vehicleId });
}

const slug = (r) => `omnidx-${r.kind}-${new Date(r.ts).toISOString().slice(0, 16).replace(/[:T]/g, '')}.txt`;

export async function shareReport(r) {
  const text = toText(r);
  const file = new File([text], slug(r), { type: 'text/plain' });

  // Prefer sharing the file so it lands in Messages/Drive/email intact.
  try {
    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({ files: [file], title: r.title });
      return;
    }
    if (navigator.share) {
      await navigator.share({ title: r.title, text });
      return;
    }
  } catch (e) {
    if (e?.name === 'AbortError') return; // user dismissed the sheet
  }
  await copyReport(r);
}

export async function copyReport(r) {
  const text = toText(r);
  try {
    await navigator.clipboard.writeText(text);
    toast('Report copied to clipboard', 'ok');
  } catch {
    // Clipboard API is blocked on insecure origins — fall back to a download.
    downloadReport(r);
  }
}

/**
 * Share or save a recorded data log as CSV. Values are quoted only when they
 * need it, and the header row is derived from every column seen in the run.
 */
export async function exportCSV(basename, samples) {
  if (!samples.length) { toast('Nothing recorded yet', 'bad'); return; }

  const cols = ['time_s', ...[...new Set(samples.flatMap((s) => Object.keys(s.values)))].sort()];
  const t0 = samples[0].t;
  const cell = (v) => {
    if (v === undefined || v === null) return '';
    const str = typeof v === 'number' ? String(Number(v.toFixed(3))) : String(v);
    return /[",\n]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
  };
  const lines = [cols.join(',')];
  for (const s of samples) {
    lines.push([((s.t - t0) / 1000).toFixed(2), ...cols.slice(1).map((c) => cell(s.values[c]))].join(','));
  }
  const text = lines.join('\n');
  const name = `${basename}-${new Date().toISOString().slice(0, 16).replace(/[:T]/g, '')}.csv`;

  const file = new File([text], name, { type: 'text/csv' });
  try {
    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({ files: [file], title: name });
      return;
    }
  } catch (e) {
    if (e?.name === 'AbortError') return;
  }
  const url = URL.createObjectURL(new Blob([text], { type: 'text/csv' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
  toast(`Saved ${samples.length} samples`, 'ok');
}

export function downloadReport(r) {
  const blob = new Blob([toText(r)], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = slug(r);
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
  toast('Report saved', 'ok');
}
